Updated sv translation (Daniel Nylander)

diff --git a/MagiskOnWSAOld/workflows/build.yaml b/MagiskOnWSAOld/workflows/build.yaml
--- a/MagiskOnWSAOld/workflows/build.yaml
+++ b/MagiskOnWSAOld/workflows/build.yaml
@@ -123,4 +123,7 @@ jobs:
                       else
                           echo -e "${{ inputs.magisk_url }}\n out=magisk-debug.zip" > "$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"
 
-                          if ! aria2c --no-conf --log-level=info --log="$DOWNLOAD_DIR/aria2_custom_magisk_download.log" -x16 -s16 -j5 -c -R -m0 --async-dns=false --check-integrity --continue --allow-overwrite --conditional-get -d"$DOWNLOAD_DIR
+                          if ! aria2c --no-conf --log-level=info --log="$DOWNLOAD_DIR/aria2_custom_magisk_download.log" -x16 -s16 -j5 -c -R -m0 --async-dns=false --check-integrity --continue --allow-overwrite --conditional-get -d"$DOWNLOAD_DIR" -i"$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"; then
+                              echo "Magisk download error!"
+                              exit 1
+                          
