yup

diff --git a/MagiskOnWSAOld/workflows/build.yaml b/MagiskOnWSAOld/workflows/build.yaml
--- a/MagiskOnWSAOld/workflows/build.yaml
+++ b/MagiskOnWSAOld/workflows/build.yaml
@@ -191,4 +191,7 @@ jobs:
                               else
                                   GAPPS_VAR="pico"
                                   echo -e "${{ inputs.gapps_url }}\n out=OpenGApps-"$ARCH"-"$GAPPS_VAR".zip" > -i"$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"
-                                  if ! aria2c --no-conf --log-level=info --log="$DOWNLOAD_DIR/aria2_gapps_download.log" -x16 -s16 -j5 -c -R -m0 --async-dns=false --check-integrity --continue --allow-overwrite --conditional-get -d"$DOWNLOAD_DIR" -i"$DOWNLO
+                                  if ! aria2c --no-conf --log-level=info --log="$DOWNLOAD_DIR/aria2_gapps_download.log" -x16 -s16 -j5 -c -R -m0 --async-dns=false --check-integrity --continue --allow-overwrite --conditional-get -d"$DOWNLOAD_DIR" -i"$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"; then
+                                      echo "OpenGApps download error!"
+                                      exit 1
+        
