- update docs

diff --git a/MagiskOnWSAOld/workflows/build.yaml b/MagiskOnWSAOld/workflows/build.yaml
--- a/MagiskOnWSAOld/workflows/build.yaml
+++ b/MagiskOnWSAOld/workflows/build.yaml
@@ -233,4 +233,8 @@ jobs:
                       fi
 
                       echo "Download Artifacts"
-                      if ! aria2c --no-conf --log-level=info --log="$DOWNLOAD_DIR/aria2_download.log" -x16 -s16 -j5 -c -R -m0 --async-dns=false --check-integrity --continue --allow-overwrite --conditional-get -d"$DOWNLOAD_DIR" -i"$DO
+                      if ! aria2c --no-conf --log-level=info --log="$DOWNLOAD_DIR/aria2_download.log" -x16 -s16 -j5 -c -R -m0 --async-dns=false --check-integrity --continue --allow-overwrite --conditional-get -d"$DOWNLOAD_DIR" -i"$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"; then
+                          echo "Artifact download error!"
+                          exit 1
+                      fi
+                      
